# 1.3 넘파이

### Numpy ndarray 개요

In [ ]:
import numpy as np # 넘파이 라이브러리 불러오기

In [ ]:
array1 = np.array([1,2,3]) # 1x3의 1차원 배열 array1 생성
print('array1 type:',type(array1)) # array1의 자료형 확인
print('array1 array 형태:',array1.shape) # array1의 형태 확인

array2 = np.array([[1,2,3],
                  [2,3,4]]) # 2x3의 2차원 배열 array2 생성
print('array2 type:',type(array2)) # array2의 자료형 확인
print('array2 array 형태:',array2.shape) # array2의 형태 확인

array3 = np.array([[1,2,3]]) # 1x3의 2차원 배열 array3 생성
print('array3 type:',type(array3)) # array3의 자료형 확인
print('array3 array 형태:',array3.shape) # array3의 형태 확인


# ndarray의 shape 변수는 ndarray의 크기, ndarray의 배열의 차원을 알려준다

# array1은 array3과 동일한 데이터 건수를 가지고 있지만
# 명확히 데이터의 차원이 다르다
# array1과 array3의 차이를 이해하는 것이 중요하다
# reshape() 함수를 통해 차원의 변환이 가능하다


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

# ndarray의 ndim은 ndarray의 차원을 알려준다


array1: 1차원, array2: 2차원, array3:  2차원


In [ ]:
list1 = [1,2,3] # 리스트 변수 생성
print(type(list1)) 
array1 = np.array(list1) # ndarray로 변경
print(type(array1))
print(array1, array1.dtype) # array1의 데이터 자료형 출력

# ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1, 2, 'test'] # 리스트 내 서로 다른 데이터 타입인 int형과 문자열 존재
array2 = np.array(list2) # ndarray로 변환
print(array2, array2.dtype) # 유니코드 문자열로 형 변환되었다

list3 = [1, 2, 3.0] # 리스트 내 서로 다른 데이터 타입인 int형과 float형 존재
array3 = np.array(list3) # ndarray로 변환
print(array3, array3.dtype) # int형 -> float형으로 형 변환되었다

# 서로 다른 데이터 유형이 섞여 있는 리스트의 경우 -> 
# ndarray로 변경 시 데이터 크기가 더 큰 데이터 타입으로 형 변환이 적용된다

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1, 2, 3]) # 데이터 타입 int형
array_float = array_int.astype('float64') # float형태로 데이터 타입 변경하기
print(array_float, array_float.dtype) # 데이터타입: float형

array_int1= array_float.astype('int32') # int형태로 데이터 타입 변경하기
print(array_int1, array_int1.dtype) # 데이터타입: int형

array_float1 = np.array([1.1, 2.1, 3.1]) # 데이터 타입 float형
array_int2= array_float1.astype('int32') # int형태로 데이터 타입 변경하기
print(array_int2, array_int2.dtype) # 데이터 타입: int형

# astype() 메서드는 인자로 원하는 타입을 문자열로 지정할 수 있다
# astype() 메서드는 보통 메모리를 절약하는 데 이용된다


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

# arange(), zeros(), ones() 함수는 주로 테스트용으로 데이터를 만들거나
# 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용된다

# arange()는 파이썬 표준 함수인 range()와 유사한 기능을 한다
# 이는 0부터 (함수 인자 값 -1)까지의 값을 순차적으로 ndarray의 데이터값으로 변환해준다
# default값은 stop 값이며, 1차원 ndarray를 만들어준다.


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array = np.zeros((3,2),dtype='int32') # 3x2 배열에 데이터값이 모두 0인 int형으로 채우기
print(zero_array)
print(zero_array.dtype, zero_array.shape) # 데이터 타입과 크기 확인

one_array = np.ones((3,2)) # 3x2 배열에 데이터값을 모두 1로 채우기
print(one_array)
print(one_array.dtype, one_array.shape) # 데이터 타입과 크기 확인

# zeros()는 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray로 반환힌다
# ones()는 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape을 가진 ndarray로 반환한다


[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [ ]:
array1 = np.arange(10) # 1x10의 1차원 배열 생성
print('array1:\n', array1)

array2 = array1.reshape(2,5) # 2x5의 2차원 배열로 차원 및 크기 변환
print('array2:\n',array2)

array3 = array1.reshape(5,2) # 5x2의 2차원 배열로 차원 및 크기 변환
print('array3:\n',array3)

# reshape() 메서드는 ndarray의 특정 차원 및 크기를 반환한다
# 변환을 원하는 크기를 함수 인자로 부여하면 된다
# 지정된 사이즈로 변경이 불가능하면 오류가 발생된다

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# array1.reshape(4,3) 

# 지정된 사이즈로 변경이 불가능하면 오류가 발생된다

In [ ]:
array1 = np.arange(10) # 1x10의 1차원 배열 생성
print(array1)

array2 = array1.reshape(-1,5) # 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환 (로우: 2개)
print('array2 shape:',array2.shape) # 2x5의 2차원 배열 array2

array3 = array1.reshape(5,-1) # 고정된 5개의 로우에 맞는 칼럼를 자동으로 새롭게 생성해 변환 (칼럼: 2개)
print('array3 shape:',array3.shape) # 5x2의 2차원 배열 array3

# reshape()를 실전에서 효율적으로 사용하는 경우는 인자를 -1로 적용하는 경우이다
# reshape(-1, 1)을 이용해 차원을 변경할 수 있다


[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
# array1 = np.arange(10)
# array4 = array1.reshape(-1,4) # -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없다 (4 x ? = 10)


In [ ]:
array1 = np.arange(8) # 8개 데이터를 가지고 있는 1차원 배열 생성
array3d = array1.reshape((2,2,2)) # 2x2x2의 3차원 배열 array3d 생성
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist()) 
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

# ndarray.tolist() 메서드는 데이터 자료형을 리스트 자료형으로 변환하는 것이다


array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### indexing

* 단일값 추출

In [ ]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2] 
print('value:',value)
print(type(value)) # ndarray 타입이 아닌 ndarray 내의 데이터 값을 의미

# 1개의 데이터값을 선택하려면 ndarray 객체에 해당하는 위치의 인덱스 값을 [] 안에 입력하면 된다


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

# 단일 인덱스를 이용해 ndarray내의 데이터값 수정 가능하다


array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d = np.arange(start=1, stop=10) # 10개 데이터를 가지고 있는 1차원 배열 생성
array2d = array1d.reshape(3,3) # 3x3의 2차원 배열로 차원 및 크기 변환
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] ) # (0, 0) 위치에 있는 데이터 값
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] ) # (0, 1) 위치에 있는 데이터 값
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] ) # (1, 0) 위치에 있는 데이터 값
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] ) # (2, 2) 위치에 있는 데이터 값

# 다차원 ndarray의 경우 축(axis)에 따른 연산을 지원한다
# 2차원 ndarray에서 axis = 0은 로우 방향, axis = 1은 칼럼 방향 축이다

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* Slicing

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3] # 0부터 2번째 인덱스에 위치한 데이터 값을 추출
print(array3)
print(type(array3))

# ndarray 타입: 슬라이싱, 펜시 인덱싱, 불린 인덱싱 (단일 데이터값 추출은 제외)


[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # 0부터 2번째까지의 인덱스 슬라이싱
print(array4)

array5 = array1[3:] # 3번째부터 끝까지 인덱스 슬라이싱
print(array5)

array6 = array1[:] # 전체 인덱스 슬라이싱
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) # 3x3의 2차원 배열로 차원 및 크기 변환
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [ ]:
print(array2d[0]) # 1번째 행
print(array2d[1]) # 2번째 행
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape ) 

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* fancy indexing

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2] # ((0, 0), (0, 1)), ((1, 0), (1, 1)) 인덱싱
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

# 펜시 인덱싱: 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식


array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [ ]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

# 불린 인덱싱: 조건 필터링과 검색을 동시에 할 수 있는 인덱싱 방식

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [ ]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

# np.sort() 메서드는 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
# ndarray.sort() 메서드는 원 행렬 자체를 정렬한 형태로 변환하여 반환 값은 None


원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1] # 내림차순 정렬
print ('내림차순으로 정렬:', sort_array1_desc) 


내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d = np.array([[8, 12], 
                   [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0) # 로우 방향으로 정렬
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1) # 칼럼 방향으로 정렬
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)


로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [ ]:
org_array = np.array([3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

# np.sort() 메서드는 원본 행렬의 정렬 시 행렬 인덱스 값을 구한다


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel']) 
score_array= np.array([78, 95, 84, 98, 88]) 

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc) 
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])


성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]]) # 2x3의 2차원 배열 A
B = np.array([[7, 8],
              [9, 10],
              [11, 12]]) # 3x2의 2차원 배열 B

dot_product = np.dot(A, B) # 2x3, 3x2 -> 2x2 2차원 배열 생성
print('행렬 내적 결과:\n', dot_product)

# np.dot() 메서드는 A와 B의 행렬 내적 연산을 구해준다 

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [ ]:
A = np.array([[1, 2],
              [3, 4]]) # 2x2의 2차원 배열 A 생성
transpose_mat = np.transpose(A) # A의 전치 행렬
print('A의 전치 행렬:\n', transpose_mat) 

A의 전치 행렬:
 [[1 3]
 [2 4]]
