In [4]:
import numpy as np

In [10]:
arr1 = np.array([1,2,3])
print(type(arr1),arr1.shape)

arr2 = np.array([[1,2,3],[4,5,6]])
print(type(arr2),arr2.shape)

arr3 = np.array([[1,2,3]])
print(type(arr3),arr3.shape)

<class 'numpy.ndarray'> (3,)
<class 'numpy.ndarray'> (2, 3)
<class 'numpy.ndarray'> (1, 3)


In [12]:
list1 = [1,2,3]
print(type(list1))
arr1 = np.array(list1)
print(type(arr1),arr1.dtype)

<class 'list'>
<class 'numpy.ndarray'> int64


In [14]:
arr_int = np.array([1, 2, 3])
arr_float = arr_int.astype('float64')
print(arr_float, arr_float.dtype)

arr_int1= arr_float.astype('int32')
print(arr_int1, arr_int1.dtype)

arr_float = np.array([1.1, 1.2, 1.3])
arr_int= arr_float.astype('int32')
print(arr_int, arr_int.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 1 1] int32


In [32]:
arr1 = np.arange(10)
arr2 = np.ones(10)
arr3 = np.zeros(10)
print(arr1,arr2,arr3)

[0 1 2 3 4 5 6 7 8 9] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
print(arr1.reshape(1,-1))
print(arr1.reshape(2,5,-1))

[[0 1 2 3 4 5 6 7 8 9]]
[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]


In [29]:
print(arr1[0],arr1[-1])
print(arr1.reshape(2,-1)[0][-1])

0 9
4


In [30]:
print(arr1[3:5],arr1.reshape(2,-1)[0:1,3:5])

[3 4] [[3 4]]


In [41]:
arr = np.arange(9).reshape(3,-1)
print(arr[[0,1,2],1])
print(arr[0:3,1])
print(arr[arr>4])
print(arr[arr%2==0])


[1 4 7]
[1 4 7]
[5 6 7 8]
[0 2 4 6 8]


In [52]:
arr = np.array([1,5,2,6,4,3])
print(np.sort(arr))
print(np.sort(arr)[::-1])
print(np.sort(arr.reshape(2,-1)))
print(np.sort(arr.reshape(2,-1),0))
print(np.sort(arr.reshape(2,-1),1))

[1 2 3 4 5 6]
[6 5 4 3 2 1]
[[1 2 5]
 [3 4 6]]
[[1 4 2]
 [6 5 3]]
[[1 2 5]
 [3 4 6]]


In [54]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],[3,4],[5,6]])
print(np.dot(arr1,arr2))
print(np.transpose(np.dot(arr1,arr2)))

[[22 28]
 [49 64]]
[[22 49]
 [28 64]]


In [56]:
import pandas as pd

In [58]:
train = pd.read_csv("/content/titanic/train.csv")
test = pd.read_csv("/content/titanic/test.csv")
train.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [63]:
print(train.shape)
train.info()
train.describe()

(891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [71]:
pclass = train['Pclass']
print(pclass.value_counts())
pclass.head(5)

3    491
1    216
2    184
Name: Pclass, dtype: int64


0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [72]:
print(train['Embarked'].value_counts())
print(train['Embarked'].value_counts(dropna=False))

S    644
C    168
Q     77
Name: Embarked, dtype: int64
S      644
C      168
Q       77
NaN      2
Name: Embarked, dtype: int64


In [82]:
arr1 = np.array([1,2,3])
df1 = pd.DataFrame(arr1,['fir','sec','thr'])
df1

0
fir  1
sec  2
thr  3

In [84]:
df2 = pd.DataFrame(arr1.reshape(1,-1),['fir'])
df2

0  1  2
fir  1  2  3

In [90]:
print(type(df2.values.tolist()))

<class 'list'>


In [96]:
print(train['Age'][0])
train['Age'][0]=10
print(train['Age'][0])
train['Age_by_10'] = train['Age']*10
train.head(3)

10.0
10.0


<ipython-input-96-9767d63c2dff>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Age'][0]=10


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  10.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      100.0  
1      0          PC 17599  71.2833   C85        C      380.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      260.0

In [99]:
train = train.drop('Age_by_10',1) #inplace = True
train.head(3)

<ipython-input-99-97211d6d60a7>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  train = train.drop('Age_by_10',1)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  10.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [106]:
train = pd.read_csv("/content/titanic/train.csv")
idx = train.index
print(idx,idx.values[:10],idx[:10].values)

RangeIndex(start=0, stop=891, step=1) [0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [108]:
fair = train['Fare']
print(fair.max(),fair.sum(),sum(fair),(fair+3).head(2))

512.3292 28693.9493 28693.949299999967 0    10.2500
1    74.2833
Name: Fare, dtype: float64


In [111]:
print(train['Pclass'].head(2))
print(train[['Survived','Pclass']].head(2))
print(train[0:2].head(2))

0    3
1    1
Name: Pclass, dtype: int64
   Survived  Pclass
0         0       3
1         1       1
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C  


In [125]:
print(train.loc[0])
print(train[train['Age']>10].head(2))
print(train[(train['Age']>10) & (train['Age']<20)].head(2))

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C  
    PassengerId  Survived  Pcl

In [132]:
print(train.sort_values(by=['Name']).head(2))
print(train.sort_values(by=['Pclass','Name'],ascending=False).head(2))

     PassengerId  Survived  Pclass                         Name   Sex   Age  \
845          846         0       3          Abbing, Mr. Anthony  male  42.0   
746          747         0       3  Abbott, Mr. Rossmore Edward  male  16.0   

     SibSp  Parch     Ticket   Fare Cabin Embarked  
845      0      0  C.A. 5547   7.55   NaN        S  
746      1      1  C.A. 2673  20.25   NaN        S  
     PassengerId  Survived  Pclass                             Name   Sex  \
868          869         0       3      van Melkebeke, Mr. Philemon  male   
153          154         0       3  van Billiard, Mr. Austin Blyler  male   

      Age  SibSp  Parch    Ticket  Fare Cabin Embarked  
868   NaN      0      0    345777   9.5   NaN        S  
153  40.5      0      2  A/5. 851  14.5   NaN        S  


In [133]:
print(train.count(),train[['Age','Fare']].mean(0))

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64 Age     29.699118
Fare    32.204208
dtype: float64


In [141]:
group = train.groupby(by='Pclass')
print(type(group))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [137]:
train.isna().head(2)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False

In [138]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [140]:
train['Cabin'] = train['Cabin'].fillna('C000')
train.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500  C000        S  
1      0   PC 17599  71.2833   C85        C

In [145]:
arr = [1,2,3]
print(list(map(lambda x : x**2,arr)))

[1, 4, 9]


In [146]:
train['Age'].apply(lambda x : 'Child' if x <= 15 else 'Adult').head(2)

0    Adult
1    Adult
Name: Age, dtype: object