In [2]:
import numpy as np

# numpy ndarray 개요 
array1 = np.array([1,2,3]) # 1차원 [] 로 표시한다. 
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]]) # 2차원 데이터 
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]]) # 2차원 데이터 [[ ]] 형태는 2차원! 
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
# ndarray 의 데이터 타입 
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
# 같은 데이터 타입만 연산이 가능함

list2 = [1, 2, 'test'] 
array2 = np.array(list2)
print(array2, array2.dtype)
# 데이터 유형이 섞여 있으면 크기가 더 큰 데이터 타입으로 변환 

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

#astype() : 데이터 형 변환 
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # 실수형으로 변환 
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')  # 정수형 변환 
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [5]:
# ndarray 편리하게 생성하기 - arrange, zeros, ones 
sequence_array = np.arange(10) # 0~9까지 ndarray 데이터로 변환 
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2),dtype='int32') # 모두 0으로 변환 
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) # 모두 1로 초기화 dtype은 float64가 디폴트 
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [6]:
# 차원과 크기를 변경하는 reshape()
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

# array1.reshape(4,3) 
# 위와 같이 지정된 사이즈로 변경 불가능시 오류 발생 

# 효율적으로 사용하는 법 : 인자로 -1 적용 
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) # 열 5로 고정 후 행을 자동으로 생성해 변환 
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1) # 행 5로 고정 후 열을 자동으로 생성해 변환 
print('array3 shape:',array3.shape)

#array1 = np.arange(10)
#array4 = array1.reshape(-1,4)
# 여기도 마찬가지로 지정된 사이즈로 변경 불가능시 오류 발생

# 자주 사용되는 형태 : reshape(-1, 1)
# 원본 형태가 어떠하더라도 2차원이고 반드시 1개의 열을 가지도록 변환 
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist()) 
# tolist() : 리스트 자료형으로 변환 

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [7]:
# 인덱싱: 특정한 데이터만 추출 
# 해당 위치의 인덱스 값을 [] 안에 입력 

# 1부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value))

print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2]) # 맨 뒤의 값은 -1

# 단일 인덱스 사용해 데이터 값 수정 가능하다. 
array1[0] = 9
array1[8] = 0
print('array1:',array1)

# 2차원에서의 데이터 추출
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) 
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

# 인덱싱 : 슬라이싱 ':'기호 사용하여 연속한 데이터 추출 
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3] # 시작 인덱스에서 종료 인덱스 -1까지 
print(array3)
print(type(array3))

array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # 맨 처음 인덱스인 0으로 간주 
print(array4) 

array5 = array1[3:] # 맨 마지막 인덱스로 간주 
print(array5)

array6 = array1[:] # 맨 처음 ~ 맨 마지막으로 간주 
print(array6)

# 2차원에서의 슬라이싱 
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

# 2차원에서 뒤에 오는 index를 없애면 1차원으로 반환됨
print(array2d[0]) # 첫번째 행 추출 
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

# 인덱싱: 팬시 인덱싱 - 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray 반환
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

# 인덱싱: 불린 인덱싱 
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5] # 필터링 조건을 [] 안에 기재 
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes] # false값은 무시하고 true 값에 해당하는 인덱스 값만 저장 
print('불린 인덱스로 필터링 결과 :', array3) # 저장된 인덱스 데이터 세트로 ndarray 조회 

indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9
[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]
불린 인덱스로 필터링 결과 : [6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]


In [8]:
# 행렬 정렬 : sort()
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 : 원 행렬 유지, 정렬된 행렬 반환 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬: 원 행렬 자체를 정렬한 형태로 변환 
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

# 내림차순 정리 : [::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

# axis = 0 행 방향 축 / axis = 1 열 방향 축 
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

# 정렬된 행렬의 인덱스를 반환하기 
# argsort(): 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 변환 
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

#예제 
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [9]:
# 행렬 내적 (행렬 곱)

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

# 전치 행렬
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 3]
 [2 4]]
