In [2]:
import numpy as np
array1=np.array([1,2,3]) #array 1에 np로
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape) #array1 의 형태 출력,얘는 1차원 array로 3개의 데이터를 가지고 있음.

array2=np.array([[1,2,3],[2,3,4]])
print('array2 array 형태:',array2.shape) #array2 의 형태 출력,얘는 2차원 array로 2개의로우*3개의 칼럼 =6개의 데이터를 가지고 있음.

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3 .shape)#array3 의 형태 출력,얘는 1개의 로우와 3개의 칼럼으로 구성된 2차원 데이터를 가지고 있음.


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


# ndarray의 데이터 타입

In [4]:
list1 = [1,2,3] 
print(type(list1)) 
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
#list 자료형을 ndarray로 변경, 이렇게 변경된 ndarray 내의 데이터값은 모두 int 32형 ,ndarray는 서로다른 데이터타입을 가지는 리스트와 달리
#데이터크기가 더 큰타입으로 형 변환을 일괄 적용함.

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2=[1,2,'test'] 
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0] #
array3=np.array(list3)
print(array3,array3.dtype)



['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
array_int =np.array([1, 2, 3])
array_float= array_int.astype('float64') #astype()으로 데이터타입 변경(보통 메모리 절약을 위해)
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)



[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray 편리하게 생성하는법-arange,zeros,ones

In [ ]:
sequence_array = np.arange(10) #arange -> 마치 for문의 range 같은 느낌으로 array를 순차적으로 범위안에서 생성해줌
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

In [7]:
#zero -> 튜플형태의 shape 를 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray 반환
zero_array = np.zeros((3,2),dtype='int32') #3x2 shape의 제로 ndarray 반환
print(zero_array)
print(zero_array.dtype, zero_array.shape) #zerro의 초기값 -> float 64

one_array = np.ones((3,2)) #ones() -> zero()에서 0대신 1로 채우는 기능
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경 하는 reshape()

In [8]:

array1= np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5) #2x5로 array1을 변환
print('array2:\n',array2)

array3 = array1.reshape(5,2) #5x2로 array1을 변환
print('array3:\n',array3)

#단 reshape는 변경불가능사이즈로 지정하면 오류뜸

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
array1.reshape(4,3)
#4x3으로는 구조상 변환불가능이라 오류뜸

ValueError: cannot reshape array of size 10 into shape (4,3)

In [10]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) #reshape에 로우인자로 -1을 넣으면 고정된 칼럼(여기선 5)에 맞게 array1의 로우까지 재구성해서 뽑아줌
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1) #reshape에 칼럼인자로 -1을 넣으면 고정된 로우(여기선 5)에 맞게 array1의 칼럼까지 재구성해서 뽑아줌
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [11]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)
#구조상 칼럼4로 알맞는 로우 뽑을 수 없으므로 에러난듯.

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

# 넘파이의 ndarray의 데이터세트 선택 -> 인덱싱(indexing)

In [12]:
#단일값 추출

# 1에서9 까지의 1차원 ndarray 생성 ->arrange로 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [13]:
array1[0] = 9
array1[8] = 0
print('array1:',array1) 

array1d = np.arange(start=1, stop=10) 
array2d = array1d.reshape(3,3) #3x3으로 ndarray 재배치
print(array2d) 

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] ) # array2d(0,0) 성분 출력(여기선 1)
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


In [15]:
#슬라이싱[a:b] -> a부터 b-1 인덱스까지 ndarray 반환
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [16]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

#슬라이싱의 시작과 종료인덱스는 생략가능함.,자동으로 각각 맨처음/마지막 인덱스로 간주함.

array6 = array1[:] #처음부터 마지막인덱스로 간주
print(array6)
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)


#2차원 array슬라이싱 -> 1차원 array 슬라이싱에서 중간에 , 가 들어가는 것만 다름.
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [17]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [18]:
#팬시인덱싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [ ]:
#불린 인덱싱

In [20]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5] #조건문 처럼 작용해서 array1d에서 5보다 큰 인덱스들만 뽑아냄
print('array1d > 5 불린 인덱싱 결과 값 :', array3)
array1d > 5


array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True])

In [21]:
#array1d>5 처럼 조건식만썼는데 ndarray 각 인덱스 값의 조건을 판단해 참거짓을 반환함.

In [25]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes] 
print('불린 인덱스로 필터링 결과 :', array3)
#불린 ndarray를 만들어서 인덱스로 입력하면 23 탭에서처럼 직접 인덱스집합을 대입한 것과 동일한 결과를 나타냄

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [23]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4) 


일반 인덱스로 필터링 결과 : [6 7 8 9]


In [6]:
import numpy as np

name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel']) #1차원 array 생성
score_array= np.array([78, 95, 84, 98, 88]) # 1차원 숫자 array 생성
#이는 넘파이가 판다스와 다르게 메타데이터를 별도 ndarray로 선언해야만 하는 특성이 있어서 그렇다.

sort_indices_asc = np.argsort(score_array) #argsort로 오름차순 정렬전 원래 행렬의 인덱스 반환가능
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [7]:
A = np.array([[1, 2, 3],  # 2차원 2x3 어레이 지정
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10], #2차원 3x2 어레이 지정
              [11, 12]])

dot_product = np.dot(A, B) #행렬곱
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [8]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A) #전치행렬 선언 
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


In [ ]:
교재 38p 까지 완료했습니다, 김지호