### Numpy ndarray 개요

In [2]:
import numpy as np

In [5]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)
#1차원 벡터
#(3,)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)
#2차원 2행 3열
#(2,3)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)
#2차원 1행 3열
#(1,3)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [6]:
array4 = np.array([1,2,3],[2,3,4])
print('array3 type:',type(array4))
print('array3 array 형태:',array4.shape)
#될리가 없다...

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [8]:
array5 = np.array([[[1,2,3],[2,3,4]],[[4,5,6],[7,8,9]]])
print('array2 type:',type(array5))
print('array2 array 형태:',array5.shape)
#3차원
#(2,2,3)
#높이,행,열

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 2, 3)


In [7]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))


array1: 1차원, array2: 2차원, array3:  2차원


In [10]:
print('array5: ',array5.ndim, '차원')

array5:  3 차원


In [11]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
#리스트와 넘파이어레이의 차이

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [13]:
list2 = [1,2,3]
print(type(list2))
array2 = np.array(list2, dtype=np.int64)
print(type(array2))
print(array2, array2.dtype)
#dtype을 이용하면 타입변경 가능

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [37]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)
#가장큰 자료형으로 변환되어서 유니코드로 전환 아마 int형이 -까지 11자리라  U11이 된듯?

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [46]:
list3 = [1, 2, 3 + 4j]
array3 = np.array(list3)
print(array3, array3.dtype)
#복소수도 변환해준다

list4 = ['1', '2', '3']
array4 = np.array(list4)
print(array4, array4.dtype)
#한자리면 유니코드 1

list5 = ['1', 2., '3']
array5 = np.array(list5)
print(array5, array5.dtype)
#float은 -까지 32자리라 u32인듯

list6 = ['1', 2.1111111111111111111111111111111111111111111111111111111111111111111111, '3']
array6 = np.array(list6)
print(array6, array6.dtype)
#역시나 한계가 있게 변하고 유니코드 자료형은 u32가 끝인듯

list7 = ['0123456789012345678901234567890123456789']
array7 = np.array(list7)
print(array7, array7.dtype)
#끝일줄알았지만 그냥 파이썬이 작은 소숫점자리를 인식못하는걸로

[1.+0.j 2.+0.j 3.+4.j] complex128
['1' '2' '3'] <U1
['1' '2.0' '3'] <U32
['1' '2.111111111111111' '3'] <U32
['0123456789012345678901234567890123456789'] <U40


In [47]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

#astype을 이용해서 dtpye변경 가능


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [52]:
array_float2 = np.array([1.9999, 2.1, 3.1])
array_int2= array_float2.astype('int32')
print(array_int2, array_int2.dtype)
#변경할때 버림한다
array_int2 = np.array([2147483648])
print(array_int2, array_int2.dtype)
array_int3= array_int2.astype('int32')
print(array_int3, array_int3.dtype)
#너무 큰 수 데이터타입 낮추면 오버플로우가 난다

[1 2 3] int32
[2147483648] int64
[-2147483648] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [53]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
#range랑 유사한 느낌



[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


test

In [62]:
sequence_array = np.arange(10,)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
#(10,)과 (10)은 차이가 없는걸로
sequence_array = np.arange(10, dtype=np.int64)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
#dtype으로 설정 가능
sequence_array = np.arange(10, dtype='int64')
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
#아래보고 알았는데 문자열로도 type설정 가능
sequence_array = np.arange((2,5), dtype='int64')
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
#잠깐 arange로 2차원 설정이 될까 망상을 해보았습니다.

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


TypeError: arange: scalar arguments expected instead of a tuple.

In [67]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

#zeros와 ones로 0과 1로 초기화 차원설정 가능
#디폴트 데이터타입은 float64

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [68]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

#reshape을 통해 차원변경 가능

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [69]:
array1.reshape(4,3)
#4*3 != 10 될리가 없다.

ValueError: cannot reshape array of size 10 into shape (4,3)

In [70]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

#-1을 통해 알아서 추정하게 할 수 있음
#편하다 ㅎ

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [71]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

#10%4 != 0 이라 안된다

ValueError: cannot reshape array of size 10 into shape (4)

In [72]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())
#tolist는 넘파이 어레이를 리스트로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [74]:
array7 = np.array(array6).reshape(-1,2, 1)
print('array7:\n',array7.tolist())
print('array7 shape:',array7.shape)
#3차원도 추측해서 알아서 변한다

array7:
 [[[0], [1]], [[2], [3]], [[4], [5]], [[6], [7]]]
array7 shape: (4, 2, 1)


### indexing

* 단일값 추출

In [75]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))
#슬리이싱으로 뽑아낸 값도 넘파이 자료형이다.

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [78]:
print(type(value.astype('int64')))
#물론 변환도 가능
a = int(value)
print(type(a))
#물론 int로 변환도 가능

<class 'numpy.int64'>
<class 'int'>


In [ ]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])
#리스트랑 동일

In [79]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)
#numpy array is mutable

array1: [9 2 3 4 5 6 7 8 0]


In [80]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


In [81]:
print('(row=0,col=0) index 가리키는 값:', array2d[0][0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0][1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1][0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2][2] )
#2차원배열처럼 생각도 가능
#하지 말자 슬라이싱때 오류난다..

(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* Slicing

In [82]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [83]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [95]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [96]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )
#벡터로 변환

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* fancy indexing

In [107]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d =>\n',array2d)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

#골라서 넣기 느낌

array2d =>
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [108]:
array6 = array2d[[1,0], 2]
print('array2d[[1,0], 2] => ',array6.tolist())
#반대로도 가능

array2d[[1,0], 2] =>  [6, 3]


* Boolean indexing

In [109]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [127]:
array4 = array1d[array1d != 5]
print('인덱싱 결과 값 :', array4)
#가능
array5 = array1d[(array1d != 5) & (array1d != 6)]
print('인덱싱 결과 값 :', array5)
#가능
# #논리연산자 &, | 사용
array5 = array1d[(array1d != 5) or (array1d != 6)]
print('인덱싱 결과 값 :', array5)
#불가능

인덱싱 결과 값 : [1 2 3 4 6 7 8 9]
인덱싱 결과 값 : [1 2 3 4 7 8 9]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
array1d > 5

In [119]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [120]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)
#자리로 필터링 가능

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [128]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)
# np.array는 원본을 안 건드린다


원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [135]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 
#슬라이싱을 통해 내림차순으로 변경

내림차순으로 정렬: [9 5 3 1]


In [136]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

#축 설정을 통해 정렬 방향 결정

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [137]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)
#argsort는 정렬했을 때 원 어레이의 인덱스를 반환

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [138]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [131]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])
#일반 인덱스 필터링과 조합
#어레이 2개 딕셔너리처럼 쓸 수 있을듯

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [141]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [142]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product2 = A@B
print('행렬 내적 결과:\n', dot_product2)
# @ 사용가능!

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [130]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


In [143]:
A = np.array([[1,2,3],
              [4,5,6]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]
