# 1-3. 넘파이

## 넘파이 ndarray 개요

In [20]:
import numpy as np    #넘파이 모듈 임포트

- 넘파이의 기반 데이터 타입은 **ndarray**  
- ndarray를 이용해 넘파이에서 **다차원 배열을 쉽게 생성, 다양한 연산 수행 가능**

- + **np.array()** : 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능 수행  
- + **ndarray.shape** : ndarray의 차원과 크기를 튜플 형태로 나타내줌.  
- + **ndarray.ndim** : 각 array의 차원 출력

In [7]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)
#[] 1차원 array
#(3,) -> 3개의 데이터

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)
#[[]] 2차원 array
#(2,3) -> 2행 3열

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)
#(1,3) -> 1행 3열

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [15]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 1차원, array3:  1차원


## ndarray의 데이터 타입

- ndarray 내의 데이터값은 숫자, 문자열, 불 값 등이 모두 가능

- + **ndarray.dtype** : 데이터 타입 확인 (ndarray는 리스트와 다르게 연산의 특성상 같은 데이터만 가능)  
- + **ndarray.astype()** : ndarray 내 데이터값의 타입 변경 (메모리를 더 절약해야 할 때 보통 이용 ex. float -> int)

In [12]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [18]:
# list2는 int형 값 1,2와 str형 문자열 test가 섞여 있음. int형 값 1,2 -> str형 문자열 '1','2'로 변환
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# list3는 int형 값 1,2와 float형 3.0이 섞여 있음. int형 값 1,2 -> float형 1. 2.로 변환
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경시 더 큰 데이터 타입으로 형 변환 일괄 적용 **(int < float < complex)**

In [19]:
# int32 -> float64
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# float64 -> int32
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

# float64 -> int32 (소수점 이하 절삭)
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

- 특정 크기, 차원을 가진 ndarray를 연속값이나 0, 1로 초기화해 쉽게 생성해야 할 경우 (주로 테스트용 데이터 생성/대규모 데이터 일괄적으로 초기화)

- + **np.arange(n)** : 파이썬 range()와 유사 ; array를 range()로 표현  
0부터 (함수인자값 n - 1)까지의 값을 순차적으로 ndarray의 데이터값으로 변환  **(start 값, stop 값 설정 가능)**
- + **np.zeros(shape)** : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
- + **np.ones(shape)** : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환  
(함수 인자로 dtype을 정해주지 않으면 float64형으로 생성)

In [22]:
sequence_array1 = np.arange(10) #0에서 9까지의 연속 숫자 값으로 구성된 1차원 ndarray 생성
print(sequence_array1)
print(sequence_array1.dtype, sequence_array1.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [23]:
zero_array = np.zeros((3,2),dtype='int32') # 3x2 행렬의 모든 element가 0인 shape를 가진 ndarray 반환 
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) # 3x2 행렬의 모든 element가 1인 shape를 가진 ndarray 반환
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape()

- + **ndarray.reshape(shape)** : ndarray를 특정 차원 및 크기로 변환. 변환을 원하는 크기를 함수 인자(행,열)로 부여하면 된다.
- + **ndarray.tolist()** : 리스트 자료형으로 변환. 시각적으로 더 이해하기 쉬울 수 있음.

In [24]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [25]:
array1.reshape(4,3) # 당연히 array1은 (10,) 데이터이므로 (4,3)과 같이 더 큰 elements를 가지는 사이즈로 변경 불가능.

ValueError: cannot reshape array of size 10 into shape (4,3)

In [41]:
array1 = np.arange(10) #array1은 1차원 ndarray로 0~9까지의 데이터를 가지고 있음
print(array1)

array2 = array1.reshape(-1,5) #10개의 elements를 충족시키기 위해 고정된 5개의 열에 2개의 행을 가지게 됨
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1) #10개의 elements를 충족시키기 위해 고정된 2개의 열에 5개의 행을 가지게 됨
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


- **-1을 인자로 사용하면, 원래 ndarray와 호환되는 새로운 shape로 변환해 준다. 고정된 행/열에 맞게 elements 수가 일치하도록 배열을 생성해주는 것이라고 생각하자.** 

- array1.reshape(-1,5)는 행 -1, 열 5의 인자를 가짐. 여기서 -1 인자는 '고정된 5개의 열'에 맞는 행을 자동으로 새롭게 생성해 변환하라는 의미  
=> 즉, 10개의 elements를 충족시키기 위해 2개의 행을 가지게 됨

- array2.reshape(5,-1)는 행 5, 열 -1의 인자를 가짐. 여기서 -1 인자는 '고정된 5개의 행'에 맞는 열을 자동으로 새롭게 생성해 변환하라는 의미  
=> 즉, 10개의 elements를 충족시키기 위해 5개의 행을 가지게 됨

In [27]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) # 10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 로우로 변경 불가. 에러 발생

ValueError: cannot reshape array of size 10 into shape (4)

- -1 인자는 reshape(-1,-1)와 같은 형태로 자주 사용됨.  **reshape(-1,1)은 2차원이고, 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장**

In [28]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist()) # tolist()는 ndarray를 리스트 자료형으로 변환

# 3차원 ndarray를 reshape를 통해 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 reshape를 통해 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

- 인덱싱 : 넘파이에서 ndarray 내의 **일부 데이터 세트나 특정 데이터만을 선택**할 수 있도록 함

1. **특정 데이터만 추출** : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
2. **슬라이싱(Slicing)** : 연속된 인덱스 상의 ndarray를 추출하는 방식이다. ':' 기호 사이에 시작 인덱스, 종료 인덱스를 표시하면 **시작 인덱스 ~ 종료 인덱스-1** 위치에 있는 데이터의 ndarray를 반환한다.
3. **팬시 인덱싱(Fancy Indexing)** : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환한다.
4. **불린 인덱싱(Boolenan Indexing)** : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 **True**에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

###  단일 값 추출

- 1개의 데이터만을 추출

- 1차원 ndarray에서 단일 값 추출하기

In [30]:
# 1부터 9(10-1)까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [31]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [32]:
# 단일 인덱스를 이용한 ndarray 내의 데이터 값 수정

array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


- 다차원 ndarray에서 단일 값 추출하기  
ex. 2차원 : 1차원 ndarray를 2차원 ndarray로 변환 후 **[row, col]** 을 이용해 2차원 ndarray에서 데이터 추출

In [39]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)  #2차원 3x3 ndarray로 변환
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


- 넘파이 ndarray에서는 로우, 칼럼 대신 정확한 표현으로 **axis 0, axis 1**을 쓴다.*

- + **axis 0** : row(행) 방향의 축
- + **axis 1** : column(열) 방향의 축
- + **axis 2** : height(높이) 방향의 축    

- [row=0,col=1] --> [axis 0=0, axis 1=1]
- 축 기반 연산에서 axis 생략시 axis 0 의미

### 슬라이싱

- ':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출할 수 있다.
- 시작 인덱스 : 종료 인덱스 => **시작 인덱스에서 종료 인덱스-1의 위치에 있는 데이터의 ndarray 반환**

In [42]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3] # index 0~2까지 추출해서 array3에 반환
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


- 슬라이싱 기호 ':' 문법

1. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
2. ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [43]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [45]:
# 2차원 ndarray에서 슬라이싱으로 데이터 접근
# ','로 행과 열 인덱스 지칭 (각각 슬라이싱한 행과 열의 교집합인 부분 출력이라고 보면 될 듯)

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [46]:
# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 axis 0의 첫 번째 로우인 1차원 ndarray 반환

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱 (Fancy Indexing)

- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

- ':' 대신에 인덱스를 직접 ','로 입력해서 슬라이싱하는 것이라고 생각

In [47]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

# array2d의 구조
# 1 2 3
# 4 5 6
# 7 8 9


array3 = array2d[[0,1], 2] # 1,2번째 행과 3번째 열의 교집합
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2] # 1,2번째 행과 1~2번째 열의 교집합
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]] # 1,2번째 행의 집합
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱 (Boolean Indexing)

- **조건 필터링과 검색을 동시에** 할 수 있어 매우 자주 사용되는 인덱싱 방식이다.

**Step 1** : array1d > 5와 같이 ndarray의 필터링 조건을 []안에 기재

**Step 2** : False 값은 무시하고 True 값에 해당하는 인덱스 값만 저장 (True 값 1이 아니라 True 값을 가진 인덱스를 저장하는 것!!)

**Step 3** : 저장된 인덱스 데이터 세트로 ndarray 조회

- for loop/if else 문보다 훨씬 간단하게 구현 가능
- **ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하면 됨**

In [49]:
array1d = np.arange(start=1, stop=10)

# [ ] 안에 array1d > 5 Boolean indexing을 적용 

array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [50]:
# 조건 필터링이 이렇게 간단한 이유

array1d > 5 # False 무시. True 값이 있는 인덱스 위치의 데이터만 반환. 즉, 인덱스 0~4는 무시하고 5~8까지의 데이터 세트 [6,7,8,9] 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [51]:
# 같은 원리를 적용해 조건문으로 부등식 대신 불린 ndarray 입력

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [52]:
indexes = np.array([5,6,7,8]) # 인덱스 집합을 직접 생성
array4 = array1d[ indexes ] # 조건문 내에 인덱스 집합 대입
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


## 행렬의 정렬 - sort()와 argrsort()

### 행렬 정렬

- 넘파이의 행렬 정렬은 np.sort()와 같이 넘파이에서 sort()를 호출하는 방식과 ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식이 있다.

- + **np.sort()** : **원 행렬은 그대로 유지**한 채 원 행렬의 정렬된 행렬을 반환
- + **ndarray.sort()** : **원 행렬 자체를 정렬**한 형태로 반환 ; 반환값은 None

In [67]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) #정렬된 행렬
print('np.sort( ) 호출 후 원본 행렬:', org_array) #원 행렬은 그대로 유지

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2) #반환값 None
print('org_array.sort( ) 호출 후 원본 행렬:', org_array) #원 행렬이 정렬되었음

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [59]:
sort_array1_desc = np.sort(org_array)[::-1] # [::-1] : 내림차순으로 정렬
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


- 행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행할 수 있다.

In [58]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

- 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용

- + **np.argsort()** : 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [61]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

# 행렬 정렬 시 [1, 3, 5, 9] -> element에 대해 원본 행렬의 index 값을 매칭했을 때 [1 0 3 2]

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [64]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1] # 내림차순으로 정렬함
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

#내림차순으로 정렬 시 [9, 5, 3, 1] -> 원본 행렬의 index값 매칭했을 때 [2 3 0 1]

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [65]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)

- 행렬 내적 = 행렬 곱
- 두 행렬 A, B의 내적은 **np.dot()**을 이용해 계산 가능

In [66]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[ 7,  8],
              [ 9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치 행렬

- 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
- **원소의 위치 : x행 y열 - > y행 x열** (원 행렬을 y=-x를 대칭축으로 뒤집는다고 생각)

- + **np.transpose()** : 전치 행렬

In [69]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
