### Numpy ndarray 개요

In [1]:
import numpy as np # 넘파이 모듈 임포트

In [2]:
# array() 함수 : 파이썬의 리스트와 같은 다양한 인자를 입력받아 ndarray로 변환
# ndarray란 넘파이 기반 데이터 타입, 넘파이에서 다차원 배열을 생성하고 다양한 연산 수행 가능

array1 = np.array([1,2,3]) # 1차원 기반 3개 데이터 
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape) # ndarray 배열의 shape 변수는 ndarray의 크기(행, 열의 수)를 튜플 형태로 가지고 있음.

array2 = np.array([[1,2,3],
                  [2,3,4]]) # 2차원 : 2개 행, 3개 열 = 6개 데이터
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]]) # 2차원([[]]의 의미) : 1개 행, 3개 열 = 3개 데이터
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

# ndium 변수는 각 array의 차원을 가짐

array1: 1차원, array2: 2차원, array3:  2차원


### ndarray의 데이터 타입

- ndarray 내의 데이터는 숫자(정수, 실수), 문자열, 불(logic) 값 등 모두 가능하다.
- 다만 한 ndarray 객체 안에는 하나의 데이터 타입만 가능하다.

#### dtype : ndarray 내 데이터 타입을 알 수 있는 속성



In [4]:
list1 = [1,2,3]
print(type(list1)) # list1 변수는 list 자료형
array1 = np.array(list1)
print(type(array1)) # array1 변수는 ndarray 자료형
print(array1, array1.dtype) # ndarray 내의 데이터 값 - 모두 정수이므로 자료형은 int32

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) # int형과 문자열이 섞여 있는 list2는 숫자형이 모두 문자열 자료형으로 변환

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # int형과 실수형이 섞여 있는 list3는 정수형이 모두 실수형 자료형으로 변환

# 즉, 한 ndarray 객체 안의 데이터는 오직 하나의 데이터 타입만 가능하며 이를 자동으로 변환한다.

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # astype() method : 배열 내 데이터 값 변환 시 원하는 타입을 문자열로 지정가능
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

- 특정 크기, 차원을 가진 ndarray를 연속값이나 0, 1로 초기화해 쉽게 생성해야 할 경우

- - arrange() : 파이썬 표준 함수 range()와 비슷한 기능 ; array를 range()로 표현하는 것

- - zeros() : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray 반환

- - ones() : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1으로 채운 해당 shape를 가진 ndarray 반환

In [7]:
sequence_array = np.arange(10) # 0~9까지 값으로 구성된 1차원 ndarray 생성
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
zero_array = np.zeros((3,2),dtype='int32') # 3x2 행렬의 모든 element가 0인 shape를 가진 ndarray 반환 
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) # 3x2 행렬의 모든 element가 1인 shape를 가진 ndarray 반환
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

- reshape() method는 ndarray를 특정 차원 및 크기로 변환한다. 변환을 원하는 크기를 함수 인자에 튜플 값(행,열)으로 부여하면 된다.

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshape(4,3) # array1은 (10,) 데이터이므로 이보다 더 큰 elements를 가지는 사이즈로 변경이 불가능하다.

ValueError: cannot reshape array of size 10 into shape (4,3)

In [11]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


array1은 1차원 ndarray로 0~9(10개)의 데이터를 가지고 있음.

- array1.reshape(-1,5)는 행 -1, 열 5의 인자를 가짐. 여기서 -1 인자는 '고정된 5개의 열'에 맞는 행을 자동으로 새롭게 생성해 변환하라는 의미
- - 즉, 10개의 elements를 충족시키기 위해 2개의 행을 가지게 됨

- array2.reshape(5,-1)는 행 5, 열 -1의 인자를 가짐. 여기서 -1 인자는 '고정된 5개의 행'에 맞는 열을 자동으로 새롭게 생성해 변환하라는 의미
- - 즉, 10개의 elements를 충족시키기 위해 5개의 행을 가지게 됨

In [12]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) # 10개를 xX4 행렬로 변환하는 것은 불가능, 에러발생

ValueError: cannot reshape array of size 10 into shape (4)

#### -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용 : 반드시 1개의 열을 가진 ndarray로 변환됨을 보장

In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist()) # tolist()는 ndarray를 리스트 자료형으로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### indexing
- ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 한다

1. 특정 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
2. 슬라이싱(Slicing) : 연속된 인덱스 상의 ndarray를 추출하는 방식이다. ':' 기호 사이에 시작 인덱스, 종료 인덱스를 표시하면 시작 인덱스 ~ 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환한다.
3. 팬시 인덱싱(Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환한다.
4. 불린 인덱싱(Boolenan Indexing) : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

#### 단일 값 추출 : 1개의 데이터만을 추출

In [14]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [15]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [16]:
# 단일 인덱스를 이용한 ndarray 내의 데이터 값 수정

array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
# 다차원 ndarray에서 단일 값 추출

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* 다차원 ndarray의 경우 axis 개념을 인지해야 한다. (3차원 직교좌표계에서는 행,열,높이로 대조)
- axis 0 : row
- axis 1 : collumb
- axis 2 : height

#### Slicing : ':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출 가능

In [18]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3] # index 0~3까지 추출해서 array3에 반환
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


- 슬라이싱 기호 ':' 문법
1. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
2. ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [19]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
# 2차원 ndarray에서 슬라이싱으로 데이터 접근

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [21]:
# 2차원 ndarray에서 뒤에오는 인덱스를 없애면 1차원 ndarray 반환

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#### fancy indexing : 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

# array2d의 구조
# 1 2 3
# 4 5 6
# 7 8 9


array3 = array2d[[0,1], 2] # 1~2번째 행과 3번째 열의 교집합
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2] # 1~2번째 행과 1~2번째 열의 교집합
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]] # 1~2번째 행의 집합
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


#### Boolean indexing : 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식
- for loop / if else 조건문보다 훨씬 간단하게 데이터 추출 구현 가능
- ndarray의 인덱스를 결정하는 [] 내에 바로 조건문 대입

In [23]:
array1d = np.arange(start=1, stop=10)

# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [24]:
# 조건 필터링이 빠른 이유

array1d > 5 # True 값만 반환하게 됨. 즉, 인덱스 0~4를 바로 무시하고 5~9까지의 값 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [25]:
# 같은 원리를 적용해서 만든 코드

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
indexes = np.array([5,6,7,8]) # 인덱스 집합을 직접 사용자가 형성
array4 = array1d[ indexes ] # 조건문 내에 인덱스 집합 대입
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

#### 행렬 정렬 : sort

- 넘파이 행렬 정렬은 넘파이 라이브러리에서 sort()를 호출하는 방법(np.sort())과 행렬 자체에서 sort()를 호출(ndarray.sort())하는 2가지 방식이 있다.

- - np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- - ndarray.sort() : 원 행렬 자체를 정렬한 형태로 반환, 자체 반환 값은 None

In [27]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [28]:
sort_array1_desc = np.sort(org_array)[::-1] # [::-1]의 의미 : 내림차순으로 정렬
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


* 행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행할 수 있다.
- 앞서 언급한 것과 같이 axis 0 = 로우, axis 1 = 칼럼을 의미

In [29]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬 행렬의 인덱스 반환 : np.argsort() 이용
- 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용
- np.argsort() : 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [30]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

# 행렬 정렬 시 [1, 3, 5, 9] 형태를 가짐.
# 기존 index 값을 매칭했을 때 [1 0 3 2] 값

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [31]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1] # 내림차순으로 정렬함을 의미
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [32]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기
- 넘파이 라이브러리는 다양한 선형대수 연산 지원

#### 행렬의 내적 (행렬의 곱)

In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B) # 2x3 matrix와 3x2 matrix끼리의 곱셈 연산 가능
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬 (행과 열 위치를 교환한 행렬)

In [34]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)

# numpy의 transpose() : matrix A의 행, 열의 위치를 바꾼다

print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
