# 넘파이 ndarray 개요

In [2]:
import numpy as np  #numpy 모듈 임포트  

In [3]:
array1 = np.array([1,2,3])                  
print('array1 type:',type(array1))  #넘파이의 기반 데이터 타입은 ndarray임.
print('array1 array 형태:',array1.shape) #array1은 1차원 array로 3개의 데이터를 가짐 => (3,)
                    
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape) #array2는 2차원 array로, 2개의 로우와 3개의 칼럼으로 구성됨 => (2,3)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape) #array3은 2차원 array로, 1개의 로우와 3개의 칼럼으로 구성됨 =>(1,3)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


# ndarray의 데이터 타입

In [5]:
#ndarray 내의 데이터 타입은 연산의 특성상 같은 데이터 타입만 가능함
list1 = [1,2,3]
print(type(list1)) 
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
#다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용
list2 = [1, 2, 'test']
array2 = np.array(list2) #int형과 string형이 섞여 있는 리스트 =>string형으로 일괄 형 변환
print(array2, array2.dtype)

list3 = [1, 2, 3.0] 
array3 = np.array(list3)  #int형과 float형이 섞여 있는 리스트 =>float형으로 일괄 형 변환
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [7]:
#astype() 메서드를 이용한 ndarray 내 데이터값의 타입 변경 => 메모리 절약 가능
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32') #int형으로 바꿨으므로 소수점 이하는 없어짐
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones
    특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성하하기 위해 arange(), zeros(),ones()를 이용함
    테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용됨

In [8]:
#arange()는 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [9]:
#zeros()와 ones()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 각각 0과 1로 채운 해당 shape를 가진 ndarray로 변환
#함수 인자로 dtype을 정해주지 않으면 default로 float64 형의 데이터로 ndarray를 채움
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape()

In [10]:
#reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환함
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
#reshape()는 지정된 사이즈로 변경이 불가능하면 오류 발생
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [12]:
#reshape()의 인자를 -1로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줌
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [13]:
#인자로 -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없음
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [14]:
#reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장함
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist()) #tolist() 메서드는 ndarray를 리스트 자료형으로 변환하기 위해 사용

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

###  단일 값 추출

In [15]:
#1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))
#인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터 추출 가능
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [16]:
#단일 인덱스를 이용해 ndarray 내의 데이터값도 간단하게 수정 가능
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
#다차원 ndarray에서 단일값 추출
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) #1차원 ndarray를 2차원의 3x3 ndarray로 변환
print(array2d)

#[axis 0, axis1]을 이용해 2차원 ndarray에서 데이터 추출
#넘파이의 다차원 ndarray는 axis 구분을 가짐. axis0이 로우 방향 축, axis1이 칼럼 방향 축임.
print('(row=0,col=0) index 가리키는 값:', array2d[0,0] ) 
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


### 슬라이싱

In [18]:
#슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입임
#':' 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1의 위치에 있는 데이터의 ndarray를 반환
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
#':'기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주함
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

#':'기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주함
array5 = array1[3:]
print(array5)

#':'기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주함
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

#2차원 데이터에서 슬라이싱
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0]) #축 한쪽에만 슬라이싱을 적용하고 다른 쪽 축에는 단일 값 인덱스 적용 =>1차원 데이터

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [21]:
#2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱

In [22]:
#팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환함
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2] #로우 축에 팬시 인덱싱인 [0,1]을, 칼럼 축에는 단일 값 인덱싱 2를 적용
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2] #로우 축에 팬시 인덱싱 [0:1]을, 칼럼 축에는 [0:2] 슬라이싱을 적용
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]] #로우 축에는 팬시 인덱싱 [0,1]을 적용
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱

In [23]:
#불린 인덱싱은 조건 필터랑과 검색을 동시에 할 수 있음
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [24]:
array1d > 5
#ndarray 객체에 조건식을 붙이면 False, True로 이뤄진 ndarray 객체가 반환됨
#따라서 조건으로 반환된 ndarray 객체를 인덱싱을 지정하는 []내에 입력하면 True 값이 있는 인덱스 위치의 데이터만 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [25]:
#위와 동일 과정
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
#위와 동일 과정
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


불린 인덱싱이 동작하는 단계

step1. array1d>5와 같이 ndarray의 필터링 조건을 []안에 기재

step2. False 값은 무시하고 True 값에 해당하는 인덱스값만 저장(유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장하는 것임)

step3. 저장된 인덱스 데이터 세트로 ndarray 조회

# 행렬의 정렬 - sort()와 argsort()

### 행렬 정렬

In [28]:
#np.sort()는 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
#ndarray.sort()는 원 행렬 자체를 정렬한 형태로 변환하며 반환값은 None임

org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [29]:
#두 방법 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬함 
#내림차순으로 정렬하기 위해서는 [::1]을 적용함

sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [30]:
#행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행할 수 있음
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

In [31]:
#np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
#내림차순 정렬 시에 원본 행렬의 인덱스를 구하기 위해서 [::1] 적용해야 함'
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [33]:
#시험 성적 순으로 학생 이름을 출력하고자 할 때 argsort()를 이용해 반환된 인덱스를 팬시 인덱싱으로 출력 가능
#이러한 방식은 넘파이의 데이터 추출에서 많이 사용

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)

두 행렬 A와 B의 내적은 왼쪽 행렬의 로우와 오른쪽 행렬의 칼럼의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값임 

왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산이 가능함


In [34]:
#두 행렬의 내적은 np.dot()을 이용해 계산 가능
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치 행렬

원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬이라고 함

In [35]:
#넘파이의 transpose()를 이용해 전치 행렬을 구할 수 있음
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
